### PR TITLE
Adds oldest, latest methods to QueryBuilder, fixes #790

### LINKED ISSUE #790: Add some methods
Add latest and oldest methods to query builder

### PR DESCRIPTION
**Pull request by yubarajshrestha**
fixes MasoniteFramework/orm#790

### CODE REVIEW

**Review by josephmancuso — CHANGES_REQUESTED** [review]
I don't really like the order by raw solution here. If we do the order by raw it won't work with postgres or sql server

```python
for field in fields:
    self.order_by(field, "desc")
```

**Comment by yubarajshrestha** [comment]
> I don't really like the order by raw solution here. If we do the order by raw it won't work with postgres or sql server
> 
> ```python
> for field in fields:
>     self.order_by(field, "desc")
> ```

Updated to `order_by`.

**Comment by BSN4** [comment]
tests?

**Comment by josephmancuso** [comment]
This looks better but will need some tests to make me feel comfortable with it

**Review by josephmancuso — CHANGES_REQUESTED** [review]
This looks better but will need some tests to make me feel comfortable with it

**Comment by yubarajshrestha** [comment]
> This looks better but will need some tests to make me feel comfortable with it

Done

**Comment by yubarajshrestha** [comment]
> This looks better but will need some tests to make me feel comfortable with it

Done

**Review by josephmancuso — APPROVED** [review]

**Pull request merged**
