### PR TITLE
Fix/637 - Fixed updating pivot table records on Many To Many relationships

### PR DESCRIPTION
**Pull request by federicoparroni**

### CODE REVIEW

**Review by josephmancuso — CHANGES_REQUESTED** [review]
Even though you couldn't replicate it. Should do the same thing to the `apply_query` method. I think that gets called when you eager load?

**Comment by federicoparroni** [comment]
Yes, I can add it to the `apply_query` method too. In the meanwhile, could you please add some tests to cover also this cases?

**Comment by federicoparroni** [comment]
@josephmancuso fixed also the `apply_query` method

**Comment by federicoparroni** [comment]
@josephmancuso hello! Do you think that this PR can be merged?

**Review by josephmancuso — APPROVED** [review]

**Comment by josephmancuso** [comment]
@federicoparroni yes it looks good. I couldn't get to this yesterday and just want to test this out before merging it. But the code review looks good 👍

**Comment by federicoparroni** [comment]
@josephmancuso thank you so much for everything you did!

**Pull request merged**
