### PR TITLE
Feature/has columns

### PR DESCRIPTION
**Pull request by JarriqTheTechie**
Added new feature has_columns()

### CODE REVIEW

**Comment by Marlysson** [comment]
@JarriqTheTechie 

The Schema class already has the "has_column" method implemented, this work for you case?

https://github.com/MasoniteFramework/orm/blob/2.0/src/masoniteorm/schema/Schema.py#L170-L185

**Comment by josephmancuso** [comment]
The schema class does but it only works for Sqlite right now.

706 builds out the rest of the databases

**Comment by josephmancuso** [comment]
Sqlite migrations are extremely complex. There's basically no alter commands in SQLite. so to make any table changes we actually have to create temporary tables, drop the existing table, create a new table and migrate the temp table data into the new table. So we had to build out the schema information into a structure that would support doing that.

#706 builds out this structure for MySQL & Postgres (while also satisfying the requirement for the model docstrings that M3 had)

**Comment by JarriqTheTechie** [comment]
I'm so used to doing everything from QueryBuilder & Model that if I don't see it there I automatically assume it doesn't exist.

**Comment by josephmancuso** [comment]
> I'm so used to doing everything from QueryBuilder & Model that if I don't see it there I automatically assume it doesn't exist.

I built everything in this library on a modular way so if the theres nothing on the query builder than its just not attached to it yet

**Comment by josephmancuso** [comment]
Will need to reopen a new PR without all the additions to the grammars

**Pull request closed without merging**
