### PR TITLE
Feature/703 - Adds ability to use nested relationships in existence relationships (has, where_has, doesnt_have, etc)

### LINKED ISSUE #703: Add dot notation for related relationships in where_has method
**Describe the bug**
Cannot use related table in where_has function, in Orator this worked: 
     
<pre><code>
@scope
def abc(self, query): 
    return query.where_has( "contract.contract_supports", lambda query: query.where(“category”, “abc”) ).get() 
</code></pre>

how can I use it in Masonite-ORM? Is there a way to fetch this?

**To Reproduce**
1. Set Model:
    <pre><code>
    Class BillingAccountProjectContracts(Model):
    @has_one('id', 'contract_id')
    def contract(self):
        return models.Contract
    @scope
    def abc(self, query):
        return query.where_has( 
              "contract.contract_supports", lambda query: query.where(“category”, “abc”)
         ).get() 
    </code></pre>
3. call defined function:
     obj = models.BillingAccountProjectContracts.abc().get()
4. See error:
     model.BillingAccountProjectContracts doesn't have this attribute.

**Expected behavior**
Return collection which match the conditions.

**Screenshots or code snippets**
None

**Desktop (please complete the following information):**
 - OS: Mac OS Monterey
 - Version 12.3 with Apple M1

**What database are you using?**
 - Type: Postgres
 - Version 12.10
 - Masonite ORM v2.11.9

**Additional context**
None

### PR DESCRIPTION
**Pull request by josephmancuso**
Closes #703

### CODE REVIEW

**Review by josephmancuso — COMMENTED** [review]
reviewed

**Comment by leannextang** [comment]
Hi there, it seems like still not working...
using dot relation is failed,
image
other one is still working.
image

Is there anything I've done wrong?

**Comment by josephmancuso** [comment]
what relationship is this? a has many?

**Comment by josephmancuso** [comment]
nvm I see the issue I will fix soon

**Comment by josephmancuso** [comment]
This will be fixed in 2.17.2

**Comment by leannextang** [comment]
Still get the same error while updated to v. 2.17.2.
Relations list below:
```
module A:
@has_one('id', 'contract_id')
    def contract(self):
        return models.Contract
@scope
    def abc(self, query):
        return query.where_has("contract.contract_supports", lambda query: query.where("category", "abc"))

module Contract:
@has_many
    def A(self):
        return models.A
@has_many('id', 'contract_id')
    def contract_supports(self):
        return models.ContractSupport

module ContractSupport:
@belongs_to('contract_id')
    def contract(self):
        return models.Contract
```

**Comment by josephmancuso** [comment]
Can you give me a better stack trace of the error? I cannot reproduce. Please double check you are updated to the latest

**Comment by leannextang** [comment]
Sure, I'd updated again but still get the same error.
Desktop :

> OS: Mac OS Monterey
> Version 12.3 with Apple M1
> Python Version: 3.10.2

Database I'm using:

> Type: Postgres
> Version 12.10
> Masonite ORM v2.17.2

Here's more detailed stack trace below:
```
@scope, where_has, related:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/homebrew/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/leanne.tang/.vscode/extensions/ms-python.python-2022.4.1/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/Users/leanne.tang/.vscode/extensions/ms-python.python-2022.4.1/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 444, in main
    run()
  File "/Users/leanne.tang/.vscode/extensions/ms-python.python-2022.4.1/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "/opt/homebrew/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 269, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/opt/homebrew/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/opt/homebrew/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/leanne.tang/Documents/Projects/Masonite-orm_test/app/services/orator_update.py", line 412, in <module>
    mysql_test_connect()
  File "/Users/leanne.tang/Documents/Projects/Masonite-orm_test/app/services/orator_update.py", line 353, in mysql_test_connect
    abc = models.A.abc().get()
  File "/Users/leanne.tang/Library/Caches/pypoetry/virtualenvs/Masonite-orm_test1-j2JSiUN2-py3.10/lib/python3.10/site-packages/masoniteorm/scopes/scope.py", line 12, in __call__
    return self.fn(instantiated, builder, *args, **kwargs)
  File "/Users/leanne.tang/Documents/Projects/Masonite-orm_test/app/models/A.py", line 99, in abc
    return query.where_has(
  File "/Users/leanne.tang/Library/Caches/pypoetry/virtualenvs/Masonite-orm_test1-j2JSiUN2-py3.10/lib/python3.10/site-packages/masoniteorm/query/QueryBuilder.py", line 1141, in where_has
    last_builder = related.query_where_exists(
TypeError: BaseRelationship.query_where_exists() missing 1 required positional argument: 'callback'
```

**Comment by josephmancuso** [comment]
> TypeError: BaseRelationship.query_where_exists() missing 1 required positional argument: 'callback'

This is the error that is confusing me because it clearly is not missing in the latest release. https://github.com/MasoniteFramework/orm/blob/2.0/src/masoniteorm/relationships/BaseRelationship.py#L83

**Comment by leannextang** [comment]
Looks like you missing a callback arg in QueryBuilder.py ln 1141.
(ln 1146 has it.)
image

**Comment by josephmancuso** [comment]
that's not the latest code

**Comment by leannextang** [comment]
Sorry, I've seen the wrong project...

**Comment by leannextang** [comment]
I'll clear the project to test again.

**Comment by josephmancuso** [comment]
Try to uninstall masonite-orm and reinstall

**Comment by leannextang** [comment]
There is another error:
image

But I've not set DB name as my user name in config, and the same code runs smoothly in last version(2.17.1).

Stack error mesages list below:
```
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/homebrew/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/leanne.tang/.vscode/extensions/ms-python.python-2022.4.1/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/Users/leanne.tang/.vscode/extensions/ms-python.python-2022.4.1/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 444, in main
    run()
  File "/Users/leanne.tang/.vscode/extensions/ms-python.python-2022.4.1/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "/opt/homebrew/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 269, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/opt/homebrew/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/opt/homebrew/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/leanne.tang/Documents/Projects/Masonite-orm-test/app/services/orator_update.py", line 412, in <module>
    mysql_test_connect()
  File "/Users/leanne.tang/Documents/Projects/Masonite-orm-test/app/services/orator_update.py", line 252, in mysql_test_connect
    _invioce(models.Contract.find(2))
  File "/Users/leanne.tang/Library/Caches/pypoetry/virtualenvs/Masonite-orm-test1-K78wQBHG-py3.10/lib/python3.10/site-packages/masoniteorm/models/Model.py", line 387, in find
    return builder.first()
  File "/Users/leanne.tang/Library/Caches/pypoetry/virtualenvs/Masonite-orm-test1-K78wQBHG-py3.10/lib/python3.10/site-packages/masoniteorm/query/QueryBuilder.py", line 1705, in first
    result = self.new_connection().query(
  File "/Users/leanne.tang/Library/Caches/pypoetry/virtualenvs/Masonite-orm-test1-K78wQBHG-py3.10/lib/python3.10/site-packages/masoniteorm/query/QueryBuilder.py", line 1949, in new_connection
    .make_connection()
  File "/Users/leanne.tang/Library/Caches/pypoetry/virtualenvs/Masonite-orm-test1-K78wQBHG-py3.10/lib/python3.10/site-packages/masoniteorm/connections/PostgresConnection.py", line 62, in make_connection
    self._connection = psycopg2.connect(
  File "/Users/leanne.tang/Library/Caches/pypoetry/virtualenvs/Masonite-orm-test1-K78wQBHG-py3.10/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server on socket "/tmp/.s.PGSQL.5432" failed: FATAL:  database "leanne.tang" does not exist
```

**Comment by leannextang** [comment]
Turns out the weird error happened before was because my poetry virtual environment...
After reset all things up, it seems dot relation still not working,
the column 'category' should be in contract_supports table.

Masonite-orm version:
image

Here's the error message:
```
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/homebrew/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/leanne.tang/.vscode/extensions/ms-python.python-2022.4.1/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/Users/leanne.tang/.vscode/extensions/ms-python.python-2022.4.1/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 444, in main
    run()
  File "/Users/leanne.tang/.vscode/extensions/ms-python.python-2022.4.1/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "/opt/homebrew/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 269, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/opt/homebrew/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/opt/homebrew/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/leanne.tang/Documents/Projects/Masonite-orm-test/app/services/orator_update.py", line 415, in <module>
    mysql_test_connect()
  File "/Users/leanne.tang/Documents/Projects/Masonite-orm-test/app/services/orator_update.py", line 356, in mysql_test_connect
    abc = models.A.abc().get()
  File "/Users/leanne.tang/Library/Caches/pypoetry/virtualenvs/Masonite-orm-test1-2UYfFVGQ-py3.10/lib/python3.10/site-packages/masoniteorm/query/QueryBuilder.py", line 1936, in get
    result = self.new_connection().query(self.to_qmark(), self._bindings)
  File "/Users/leanne.tang/Library/Caches/pypoetry/virtualenvs/Masonite-orm-test1-2UYfFVGQ-py3.10/lib/python3.10/site-packages/masoniteorm/connections/PostgresConnection.py", line 162, in query
    raise QueryException(str(e)) from e
masoniteorm.exceptions.QueryException: column contracts.category does not exist
```

**Comment by josephmancuso** [comment]
Ok I will take a look at this

**Comment by josephmancuso** [comment]
I created a new issue I will work on it when I have time

**Pull request merged**
