### PR TITLE
migration_directory

### LINKED ISSUE #254: Be able to specify migration path for migrations
Currently, databases/migration is hard coded in the migration class. Should be able to specify one in any migration commands that require it

### PR DESCRIPTION
**Pull request by Qubhis**
Closes #254 removing hardcoded databases/migration and replacing with relevant parameter

### CODE REVIEW

**Comment by josephmancuso** [comment]
Also added a fix where migration queries were not logging that I found when testing this pr

**Comment by josephmancuso** [comment]
Also added directory options to the command classes

**Review by josephmancuso — APPROVED** [review]

**Comment by josephmancuso** [comment]
Looks great! thank you!!

**Comment by Qubhis** [comment]
Glad to help :)

**Pull request merged**
