### PR TITLE
Adds function increment_each. This allows specifying multiple columns to increment by

### PR DESCRIPTION
**Pull request by JarriqTheTechie**
Adds function increment_each. This allows specifying multiple columns to increment by

e.g.

The following will increment the users age by 5 and its children by 10.

User.find(1).increment_each([
 {"age": 5},
 {"children", 10}
])

the result of the action returns either model or a querybuilder

This change also rewrites the original increment function to use the new increment_each function. The function signature remains intact.

### CODE REVIEW

**Comment by JarriqTheTechie** [comment]
@josephmancuso please review. If this is merged I'll create a PR for decrement_each also.

**Review by josephmancuso — CHANGES_REQUESTED** [review]
needs tests

**Comment by yubarajshrestha** [comment]
@JarriqTheTechie fix the conflicts.

**Comment by JarriqTheTechie** [comment]
I will work on correcting the conflicts and writing some tests this week if time permits.

**Comment by JarriqTheTechie** [comment]
Closing this PR. Will open a new one.

**Pull request closed without merging**
