### PR TITLE
Add a new model attribute, __uuid_bytes__, to force bytes UUID generation

### PR DESCRIPTION
**Pull request by stoutput**

### CODE REVIEW

**Comment by stoutput** [comment]
Sorry, can't run tests locally yet. I'll work on addressing failures tomorrow.

**Comment by josephmancuso** [comment]
Ok np

**Comment by stoutput** [comment]
Alright, good to go 👍

**Comment by stoutput** [comment]
Associated docs PR: https://github.com/MasoniteFramework/orm-docs/pull/33

**Review by josephmancuso — APPROVED** [review]

**Comment by josephmancuso** [comment]
LGTM 👍

**Pull request merged**
