### PR TITLE
Collection: Implement chunk, merge, get & collapse 

### PR DESCRIPTION
**Pull request by corentinalcoy**

### CODE REVIEW

**Review by josephmancuso — CHANGES_REQUESTED** [review]
Just needs a test

**Comment by corentinalcoy** [comment]
> Just needs a test

Which test?

**Comment by josephmancuso** [comment]
for chunking

**Comment by josephmancuso** [comment]
Is there supposed to be more

**Comment by corentinalcoy** [comment]
> Is there supposed to be more


> Is there supposed to be more

Done. I think I had already pushed this part before to do the PR

**Pull request closed without merging**
