### PR TITLE
Feature/64 Implementing touch() method in Model.

### LINKED ISSUE #64: Add touching to model
This should simply set the updated at

### PR DESCRIPTION
**Pull request by Marlysson**
Close #64 
@josephmancuso I only update the "updated_at" attribute. 
But it's needed verify if model is created, if already exists some "updated_at" in "dirty" attribute?

To a preliminary implementation I've used datetime native type, should we use pendulum as date manipulation library?

### CODE REVIEW

**Comment by Marlysson** [comment]
@josephmansuso

Should I use just ```updated_at = "now"``` instead set the datetime directly?

Besides tests, does lack something in implementation?

**Comment by josephmancuso** [comment]
> Should I use just updated_at = "now" instead set the datetime directly?

I don't think that will actually work. I think i did make a test for it but I don't think its valid SQL.

This just needs a test and its good to go

**Comment by Marlysson** [comment]
Is it the test: "save" a model and when "recover" it should returns with updated_at equals the set before?

**Comment by josephmancuso** [comment]
not sure what you mean. Touch should just update the updated_at and save

**Comment by josephmancuso** [comment]
pushed some changes and added a few tests

**Review by josephmancuso — APPROVED** [review]

**Pull request merged**
