### PR TITLE
fixed pivot serializing

### PR DESCRIPTION
**Pull request by josephmancuso**
Need to work through a little bit more of this ..

The first thing is we need to hide relationship data somehow. For example, apart of the pivot information you have access to the pivot data 

Screen Shot 2021-06-15 at 11 18 56 PM

I feel you may or may not want to return this data. For example, to an API response.

To solve this i added a new property:

```python
__relationship_hidden__ = {"people": ['pivot']}
```

This hides the `pivot` key from the `people` pivot table serialization

This PR also fixes a few issues i found with the belongs to many relationship

### CODE REVIEW

**Comment by yubarajshrestha** [comment]
> Need to work through a little bit more of this ..
> 
> The first thing is we need to hide relationship data somehow. For example, apart of the pivot information you have access to the pivot data
> 
> Screen Shot 2021-06-15 at 11 18 56 PM
> 
> I feel you may or may not want to return this data. For example, to an API response.
> 
> To solve this i added a new property:
> 
> ```python
> __relationship_hidden__ = {"people": ['pivot']}
> ```
> 
> This hides the `pivot` key from the `people` pivot table serialization
> 
> This PR also fixes a few issues i found with the belongs to many relationship

Hiding pivot is a good idea, most of the times we just don't need those fields. But in some cases we also add more extra fields in pivot table I will give you an example hopefully that will make sense.

```python
class User(Model):
    """User Model."""
    @belongs_to_many('user_id', 'department_id', 'id', 'id')
    def departments(self):
        from app.models.Department import Department
        return Department
```

```python
class Department(Model):
    """User Model."""
    @belongs_to_many('department_id', 'user_id', 'id', 'id')
    def users(self):
        from app.User import User
        return User
```

Following is the pivot table and simple we don't usually need any model for this separately because we just use ORM relationship features to get the pivot data from the related tables.

```python
with self.schema.create("department_user") as table:
    table.increments("id")
    table.unsigned_integer('department_id').index('department_id')
    table.foreign('department_id').references('id').on('departments').on_delete('cascade')
    table.unsigned_integer('user_id').index('user_id')
    table.foreign('user_id').references('id').on('users').on_delete('cascade')
    table.boolean('is_head').default(False)
    table.timestamps()
```

So in above pivot table there is one extra field **is_head**. The concept is, user can have involved in different departments and he/she can also be the the **department head** in multiple departments in this scenario **is_head** field in pivot table makes sense.
This is just a simple example but in ecommerce sites we encounter so many cases like this.

```python
User.with_('departments').get()
```

Expected result with above query:

```json
[{
    "id": 1,
    "departments": [
        {
            "id": 1,
            "pivot": {
                "user_id": 1,
                "department_id": 1,
                "is_head": true
            }
        },
        {
            "id": 2,
            "pivot": {
                "user_id": 1,
                "department_id": 2,
                "is_head": false
            }
        },
    ]
}]
```
Expected result after hiding pivot field:

```json
[{
    "id": 1,
    "departments": [
        {
            "id": 1,
        },
        {
            "id": 2,
        },
    ]
}]
```

I hope all the above examples will help to understand the scenario.

**Review by yubarajshrestha — APPROVED** [review]
How about adding extra pivot field?

**Review by yubarajshrestha — APPROVED** [review]

**Review by yubarajshrestha — DISMISSED** [review]

**Comment by josephmancuso** [comment]
The last part of this is getting the extra field information in

**Review by josephmancuso — COMMENTED** [review]
reviewed

**Comment by josephmancuso** [comment]
@yubarajshrestha 

The solution i came up with is to add a new `with_fields` attribute to the `belongs_to_many` relationship:

```python
    @belongs_to_many('user_id', 'department_id', 'id', 'id', with_fields=['is_head'])
    def departments(self):
        from app.models.Department import Department
        return Department
```

You can then loop through the relation and access the pivot data:

```python
for department in User.find(1).departments:
    department.pivot.is_head #== 1 or 0
```

**Comment by yubarajshrestha** [comment]
> @yubarajshrestha
> 
> The solution i came up with is to add a new `with_fields` attribute to the `belongs_to_many` relationship:
> 
> ```python
>     @belongs_to_many('user_id', 'department_id', 'id', 'id', with_fields=['is_head'])
>     def departments(self):
>         from app.models.Department import Department
>         return Department
> ```
> 
> You can then loop through the relation and access the pivot data:
> 
> ```python
> for department in User.find(1).departments:
>     department.pivot.is_head #== 1 or 0
> ```

Solution looks nice, I will give it a try, thank you.

**Comment by yubarajshrestha** [comment]
@josephmancuso looks like pivot serialization issue has been fixed. But there are still few bugs,

```json
{
  "id": 4,
  "company_id": null,
  "name": "Random User",
  "code": "USR00003",
  "email": "abc@xyz.com",
  "password": "$2b$12$Ww.AQyCRVTMPEUo65iFSEObUxM3EGQyeqkSrCd4CZR5q.dTTyzTVe",
  "remember_token": null,
  "verified_at": null,
  "status": "active",
  "status_remarks": null,
  "created_at": "2021-06-20T11:08:26+00:00",
  "updated_at": "2021-06-20T11:08:26+00:00",
  "role_id": 2,
  "role": {
    "id": 2,
    "company_id": null,
    "name": "Admin",
    "slug": "admin",
    "description": "",
    "status": "active",
    "created_at": "2021-06-20T10:54:01.855877+00:00",
    "updated_at": "2021-06-20T10:54:01.855877+00:00"
  },
  "departments": [{
      "id": 1,
      "company_id": null,
      "name": "Engineering",
      "status": "active",
      "created_at": "2021-06-20T11:07:37+00:00",
      "updated_at": "2021-06-20T11:07:37+00:00",
      "user_id": 4,
      "department_id": 2,
      "pivot": {
        "user_id": 4,
        "department_id": 2,
        "id": 1,
        "is_head": true
      }
  },
  {
    "id": 2,
    "company_id": null,
    "name": "Accounting",
    "status": "active",
    "created_at": "2021-06-20T11:07:27+00:00",
    "updated_at": "2021-06-20T11:07:27+00:00",
    "user_id": 4,
    "department_id": 1
  }]
}
```

as you can see on the above sample pivot is missing in the second object. And also the pivot object sometimes it shows there and sometimes doesn't.

**Comment by josephmancuso** [comment]
That second record definitely has a pivot record?

**Comment by yubarajshrestha** [comment]
> That second record definitely has a pivot record?

Yes, as you can see, user belongs to multiple departments. if user id is 1, and the two department ids are 5 and 6 respectively then in database pivot it is stored as [user_id, department_id] i.e, [1,5] and [1,6] right?

**Comment by josephmancuso** [comment]
Or should that pivot record be an empty dictionary?

**Comment by yubarajshrestha** [comment]
> Or should that pivot record be an empty dictionary?

Data are stored as I explained in the above message. so empty dictionary? I didn't get it.

**Comment by josephmancuso** [comment]
@yubarajshrestha I can't replicate this.

When i said should it be an empty dictionary i was saying does the 2nd user have a record inside the pivot table.

If they do not have a pivot record that is the only way i can replicate the issue.

Anyway you can provide more info? Like database screenshots of the users table, pivot table and foreign table?

**Comment by yubarajshrestha** [comment]
> @yubarajshrestha I can't replicate this.
> 
> When i said should it be an empty dictionary i was saying does the 2nd user have a record inside the pivot table.
> 
> If they do not have a pivot record that is the only way i can replicate the issue.
> 
> Anyway you can provide more info? Like database screenshots of the users table, pivot table and foreign table?

I think you misunderstood. There's only one user in database and has relations with departments.

**Comment by josephmancuso** [comment]
Maybe. Let's step back a bit.

> as you can see on the above sample pivot is missing in the second object. 

But you just said the user does not have a pivot record. The second user should not have a pivot record as they don't have a department ..

**Comment by yubarajshrestha** [comment]
> Maybe. Let's step back a bit.
> 
> > as you can see on the above sample pivot is missing in the second object.
> 
> But you just said the user does not have a pivot record. The second user should not have a pivot record as they don't have a department ..

:) Let me explain it to you properly.

1. There's only one user in users table.
2. There are multiple records in departments table.
3. The only user we had in database is involved in 2 departments. 
4. Pivot table has two records. 
5. In above json output, you can see a single user has 2 departments, on which first department has pivot shown but in second one it is not shown.
6. Above json is output of only one user with role and departments. for which the query was: 

```python
result = User.with_("role", "departments").first()
```

**Comment by josephmancuso** [comment]
gotchaaa. I See now lol. Thanks. I'll take a look then

**Comment by josephmancuso** [comment]
@yubarajshrestha Thanks for the detailed feedback. The issue was that somehow i hard coded `pivot` as an attribute that should not be serialized .. must have forgot to remove it during testing.

This is fixed in version 1.0.52

**Comment by yogesh-acharya** [comment]
Was this fix removed in latest upgrades ,, having with_fields in belongs to many relation does not give those fields .

**Pull request merged**
