### PR TITLE
Added new methods to builder (#748)

### PR DESCRIPTION
**Pull request by maicol07**
The following methods have been implemented from #748:
- `unsigned_big_integer`
- `id`
- `foreign_id`
- `foreign_id_for`
- `foreign_uuid`

### CODE REVIEW

**Comment by josephmancuso** [comment]
Just have to fix the tests

**Comment by maicol07** [comment]
@josephmancuso should be fixed!

**Comment by maicol07** [comment]
This time they're fixed for good!

**Comment by josephmancuso** [comment]
I don't see a test for the `foreign_id_for` one. Just need to make sure the model name and primary key is correctly formed.

More tests the better. Allows me to make changes with comfort

**Comment by maicol07** [comment]
How can I create a Model in tests? Should I just have to create a new model instance?

**Comment by josephmancuso** [comment]
Yup just make a model as you normally would inside the test file and use it.

Example: https://github.com/MasoniteFramework/orm/blob/2.0/tests/mysql/relationships/test_belongs_to_many.py#L16-L23

**Comment by maicol07** [comment]
@josephmancuso done!

**Review by josephmancuso — APPROVED** [review]

**Review by josephmancuso — APPROVED** [review]

**Pull request merged**
