### PR TITLE
implement migrate:fresh

### PR DESCRIPTION
**Pull request by eaguad1337**
Implements #860

I tested it on MySQL, SQLite and Postgres because I had problems running tests. Hopefully you can help me with this tests @josephmancuso

### CODE REVIEW

**Review by josephmancuso — APPROVED** [review]

**Comment by josephmancuso** [comment]
i just spent a good amount of time trying to get this to work ecause my tables all had foreign key constraints with eachother

**Comment by eaguad1337** [comment]
> i just spent a good amount of time trying to get this to work ecause my tables all had foreign key constraints with eachother

I added a `ignore_fk` param and I realized that Postgres fails when trying to use `enable_foreign_key_constraints` because this method is not implemented. I returned true if sql is None. Let me know if makes sense to you.

**Comment by josephmancuso** [comment]
hmm now these tests are failing

**Comment by eaguad1337** [comment]
removed workaround for not implemented methods in mssql and postgres @josephmancuso

**Comment by yubarajshrestha** [comment]
@eaguad1337 please fix the linter issues, I believe it's good to have this feature in the framework.

**Review by josephmancuso — APPROVED** [review]
LGTM

**Pull request merged**
