### PR TITLE
Added new method | get_column_listing()

### PR DESCRIPTION
**Pull request by JarriqTheTechie**
Get the column listing for a given table.

### CODE REVIEW

**Comment by JarriqTheTechie** [comment]
@josephmancuso Ready for review!

**Review by josephmancuso — COMMENTED** [review]
I think this functionality is being done in https://github.com/MasoniteFramework/orm/pull/706 so i don't want to duplicate work

**Comment by josephmancuso** [comment]
although slightly different in https://github.com/MasoniteFramework/orm/pull/706 (this is just getting column names when #706 is getting the full table definition for another open issue) the functionality is the same and you should be able to just pluck out the column keys from the schema built

**Comment by JarriqTheTechie** [comment]
Okay sounds good. Will #706 work in QueryBuilder and Model? That's the primary reason for the PR. I'm planning to roll out my own adminpanel and that functionality would be awesome if built-in.

**Comment by josephmancuso** [comment]
right that's what this does. It wouldn't in terms of the requirement of that PR but it would be able to. 

Right now its on the schema class so now you would do this

```python
from config.database import DB

columns = DB.get_schema_builder().get_columns("users")
```

The query builder should have access to that DB class so we can build a query builder method around this

**Comment by josephmancuso** [comment]
I'm testing #706 now. Its a draft but i think its done and if its not i'll wrap things up on it

**Comment by JarriqTheTechie** [comment]
Exquisite. I'll roll with with this implementation until #706 is merged. Great work.

**Pull request closed without merging**
